<a href="https://colab.research.google.com/github/LS10432/PDDS-PYD-0825-06Oct2025B/blob/main/Project/PI/PI02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Consolidated

In [35]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Define the local path and the URL for the covid dataset
local_path = '/content/owid-covid-data.csv'
covid_url = 'https://lms.educlaas.com/assets/courseware/v1/e206258dd748e86b8bb35fc039e90fa8/asset-v1:EduCLaSS+PYD+PDDS-PYD-0825-06Oct2025B+type@asset+block/owid-covid-data.csv'

try:
    # Try to read the Titanic dataset from the local path
    df = pd.read_csv(local_path)
    print(f"Successfully loaded data from {local_path}")
    print("\n")
except FileNotFoundError:
    # If the local file is not found, read the dataset from the URL
    df = pd.read_csv(covid_url)
    print(f"Local file not found. Loading data from {covid_url}")
    print("\n")

print(f"Total number of columns: {df.shape[1]}")
print(f"Total number of rows: {df.shape[0]}")

# Print a newline followed by a separator line
print("\n" + "="*60)
print("Display the first 5 rows of the DataFrame.")
# Print a newline followed by a separator line
print("\n" + "="*60)
# Print the first 5 rows of the DataFrame
display(df.head())

# Print a newline followed by a separator line
print("\n" + "="*60)
print("Display the last 5 rows of the DataFrame.")
# Print a newline followed by a separator line
print("\n" + "="*60)
# Print the last 5 rows of the DataFrame
display(df.tail())

print("\n" + "="*60)
print("Identify columns with missing values:\n")

# Identify and count missing values in each column
print(df.isnull().sum())
# Print a newline followed by a separator line
print("\n" + "="*60)

# Calculate columns no missing values
missing_cols = df.isnull().sum() != 0

# Display columns no missing values
print(f"Number of columns with no missing values: {len(missing_cols) - missing_cols.sum()}")
print("Column Names with no missing values:")
display(missing_cols[missing_cols == False].index.tolist())

# Print columns missing values
print("\n" + "="*60)
print(f"Number of columns with missing values: {missing_cols.sum()}")

# Calculate percentage of columns with more than 90% missing values.
missing_values_percentage = df.isnull().mean() * 100
columns_to_drop = missing_values_percentage[missing_values_percentage > 90].index.tolist()

# Display columns with more than 90% missing values
print(f"Number of columns with more than 90% missing values: {len(columns_to_drop)}")
print("Column Names with more than 90% missing values:")
print(columns_to_drop)
print("\n" + "="*60)

print("\n"+"="*60)
# Print number of columns to be dropped
print(f"Number of columns to be dropped: {len(columns_to_drop)}")
print("Column Names to be dropped:")
print(columns_to_drop)
print("\n"+"="*60)

# Remove columns with more than 90% missing values
df = df.drop(columns=columns_to_drop)

# Print a newline
print("Display the columns info after drop:")
print("\n")

# Display the columns after drop
print(df.info())
#display(df.columns)

# Print number of columns remaining
print("\n"+"="*60)
print(f"Number of columns after removal: {df.shape[1]}")
print("\n"+"="*60)

# Print a newline followed by a separator line
print("\n" + "="*60)
# Display the data type of the 'date' column
print(f"Data type of 'date' column before conversion: {df['date'].dtype}")

# Print a newline followed by a separator line
print("\n" + "="*60)
print("Column info before conversion:")
print("\n")
# Display summary of the DataFrame
df.info()

# Convert the 'date' column from object type to datetime type
df['date'] = pd.to_datetime(df['date'])

# Print a newline followed by a separator line
print("\n" + "="*60)
# Display the updated data type of the 'date' column
print(f"Data type of 'date' column after conversion: {df['date'].dtype}")

# Print a newline followed by a separator line
print("\n" + "="*60)
print("Column info after conversion:")
print("\n")
# Display summary of the DataFrame
df.info()

print("\n" + "="*60)

# Identify and count missing values in each column
missing_values_per_column = df.isnull().sum()

# Calculate columns with missing values
missing_cols_count = missing_values_per_column[missing_values_per_column != 0].count()

# Calculate numerical and non-numerical columns with missing values
numerical_cols_with_missing = df.select_dtypes(include=['float64', 'int64']).columns[df.select_dtypes(include=['float64', 'int64']).isnull().any()]
categorical_cols_with_missing = df.select_dtypes(include=['object']).columns[df.select_dtypes(include=['object']).isnull().any()]

# Display number of columns missing values and numerical and non-numerical columns with missing values
print(f"Total number of columns: {df.shape[1]}")
print(f"Number of columns with missing values: {missing_cols_count}")
print(f"Number of numerical columns with missing values: {len(numerical_cols_with_missing)}")
print(f"Number of non-numerical columns with missing values: {len(categorical_cols_with_missing)}")
print("\n" + "="*60)

# Select numerical columns
print(f"Number of numerical columns with missing values: {len(numerical_cols_with_missing)}")
print("Use the built-in mean() function to replace missing values in numerical columns. Mean is a common method for imputing missing numerical values when the data is not heavily skewed, as it represents the central tendency of the data.")

# Impute missing values in numerical columns using the mean
for col in numerical_cols_with_missing:
  mean_val = df[col].mean()
  df[col] = df[col].fillna(mean_val)

# Print the number of remaining missing values per column fter numerical imputation
print("\nNumber of remaining missing values per column after numerical imputation:")
print(df.isnull().sum())
print("\n" + "="*60)

# Select categorical columns
print(f"Number of non-numerical columns with missing values: {len(categorical_cols_with_missing)}")
print("Use the built-in mode() function to replace missing values in non-numerical columns. Mode is suitable for categorical columns as it represents the most frequent category, making it ideal for filling missing values in discrete data where mean is not applicable.")

# Impute missing values in categorical columns using the mode
for col in categorical_cols_with_missing:
  mode_val = df[col].mode()[0] # mode() can return multiple values, take the first
  df[col] = df[col].fillna(mode_val)

# Print the number of remaining missing values per column
print("\nNumber of remaining missing values per column after non-numerical imputation:")
print(df.isnull().sum())

print("\n" + "="*60)

# Get the number of rows before removing duplicates
rows_before = df.shape[0]
print(f"Number of rows before removing duplicates: {rows_before}")

# Count the number of duplicate rows
duplicate_rows = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_rows}")

# Remove duplicate rows
df = df.drop_duplicates()

# Get the number of rows after removing duplicates
rows_after = df.shape[0]
print(f"Number of rows after removing duplicates: {rows_after}")

# Extract year and month from the 'date' column
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month

# Display the head of the DataFrame to show the new columns
print("\n" + "="*60)
print("Display the first 5 rows of the DataFrame with 'year' and 'month' columns.")
print("\n" + "="*60)
display(df.head())

print("\n" + "="*60)
df.info()

# Get unique countries from the 'location' column
unique_countries = df['location'].unique()

# Count the number of unique countries
num_unique_countries = len(unique_countries)

print("\n" + "="*60)
# Print the total count of unique countries
print(f"Total number of unique countries: {num_unique_countries}")
print("\n" + "="*60)

# Display the list of unique countries
print("\nList of unique countries:")
print(unique_countries)

Local file not found. Loading data from https://lms.educlaas.com/assets/courseware/v1/e206258dd748e86b8bb35fc039e90fa8/asset-v1:EduCLaSS+PYD+PDDS-PYD-0825-06Oct2025B+type@asset+block/owid-covid-data.csv


Total number of columns: 67
Total number of rows: 358838

============================================================
Display the first 5 rows of the DataFrame.

============================================================

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-03,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-04,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-05,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-06,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-07,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN

============================================================
Display the last 5 rows of the DataFrame.

============================================================

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
358833,ZWE,Africa,Zimbabwe,2023-11-18,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358834,ZWE,Africa,Zimbabwe,2023-11-19,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358835,ZWE,Africa,Zimbabwe,2023-11-20,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358836,ZWE,Africa,Zimbabwe,2023-11-21,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358837,ZWE,Africa,Zimbabwe,2023-11-22,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN

============================================================
Identify columns with missing values:

iso_code                                        0
continent                                   17108
location                                        0
date                                            0
total_cases                                 38210
                                            ...
population                                      0
excess_mortality_cumulative_absolute       346627
excess_mortality_cumulative                346627
excess_mortality                           346627
excess_mortality_cumulative_per_million    346627
Length: 67, dtype: int64

============================================================
Number of columns with no missing values: 4
Column Names with no missing values:

['iso_code', 'location', 'date', 'population']

============================================================
Number of columns with missing values: 63
Number of columns with more than 90% missing values: 8
Column Names with more than 90% missing values:
['weekly_icu_admissions', 'weekly_icu_admissions_per_million', 'weekly_hosp_admissions', 'weekly_hosp_admissions_per_million', 'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative', 'excess_mortality', 'excess_mortality_cumulative_per_million']

============================================================

============================================================
Number of columns to be dropped: 8
Column Names to be dropped:
['weekly_icu_admissions', 'weekly_icu_admissions_per_million', 'weekly_hosp_admissions', 'weekly_hosp_admissions_per_million', 'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative', 'excess_mortality', 'excess_mortality_cumulative_per_million']

============================================================
Display the columns info after drop:


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 358838 entries, 0 to 358837
Data columns (total 59 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    358838 non-null  object
 1   continent                                   341730 non-null  object
 2   location                                    358838 non-null  object
 3   date                                        358838 non-null  object
 4   total_cases                                 320628 non-null  float64
 5   new_cases                                   349032 non-null  float64
 6   new_cases_smoothed                          347773 non-null  float64
 7   total_deaths                                299086 non-null  float64
 8   new_deaths                                  349089 non-null  float64
 9   new_deaths_smoothed                         347859 non-null  float64
 10  total_cases_per_million                     320628 non-null  float64
 11  new_cases_per_million                       349032 non-null  float64
 12  new_cases_smoothed_per_million              347773 non-null  float64
 13  total_deaths_per_million                    299086 non-null  float64
 14  new_deaths_per_million                      349089 non-null  float64
 15  new_deaths_smoothed_per_million             347859 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                37853 non-null   float64
 18  icu_patients_per_million                    37853 non-null   float64
 19  hosp_patients                               39263 non-null   float64
 20  hosp_patients_per_million                   39263 non-null   float64
 21  total_tests                                 79387 non-null   float64
 22  new_tests                                   75403 non-null   float64
 23  total_tests_per_thousand                    79387 non-null   float64
 24  new_tests_per_thousand                      75403 non-null   float64
 25  new_tests_smoothed                          103965 non-null  float64
 26  new_tests_smoothed_per_thousand             103965 non-null  float64
 27  positive_rate                               95927 non-null   float64
 28  tests_per_case                              94348 non-null   float64
 29  tests_units                                 106788 non-null  object
 30  total_vaccinations                          80162 non-null   float64
 31  people_vaccinated                           76724 non-null   float64
 32  people_fully_vaccinated                     73420 non-null   float64
 33  total_boosters                              48358 non-null   float64
 34  new_vaccinations                            66124 non-null   float64
 35  new_vaccinations_smoothed                   184057 non-null  float64
 36  total_vaccinations_per_hundred              80162 non-null   float64
 37  people_vaccinated_per_hundred               76724 non-null   float64
 38  people_fully_vaccinated_per_hundred         73420 non-null   float64
 39  total_boosters_per_hundred                  48358 non-null   float64
 40  new_vaccinations_smoothed_per_million       184057 non-null  float64
 41  new_people_vaccinated_smoothed              183804 non-null  float64
 42  new_people_vaccinated_smoothed_per_hundred  183804 non-null  float64
 43  stringency_index                            197651 non-null  float64
 44  population_density                          304672 non-null  float64
 45  median_age                                  283301 non-null  float64
 46  aged_65_older                               273432 non-null  float64
 47  aged_70_older                               280461 non-null  float64
 48  gdp_per_capita                              277692 non-null  float64
 49  extreme_poverty                             179007 non-null  float64
 50  cardiovasc_death_rate                       278348 non-null  float64
 51  diabetes_prevalence                         292517 non-null  float64
 52  female_smokers                              208840 non-null  float64
 53  male_smokers                                206000 non-null  float64
 54  handwashing_facilities                      136345 non-null  float64
 55  hospital_beds_per_thousand                  245760 non-null  float64
 56  life_expectancy                             330161 non-null  float64
 57  human_development_index                     269789 non-null  float64
 58  population                                  358838 non-null  float64
dtypes: float64(54), object(5)
memory usage: 161.5+ MB
None

============================================================
Number of columns after removal: 59

============================================================

============================================================
Data type of 'date' column before conversion: object

============================================================
Column info before conversion:


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 358838 entries, 0 to 358837
Data columns (total 59 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    358838 non-null  object
 1   continent                                   341730 non-null  object
 2   location                                    358838 non-null  object
 3   date                                        358838 non-null  object
 4   total_cases                                 320628 non-null  float64
 5   new_cases                                   349032 non-null  float64
 6   new_cases_smoothed                          347773 non-null  float64
 7   total_deaths                                299086 non-null  float64
 8   new_deaths                                  349089 non-null  float64
 9   new_deaths_smoothed                         347859 non-null  float64
 10  total_cases_per_million                     320628 non-null  float64
 11  new_cases_per_million                       349032 non-null  float64
 12  new_cases_smoothed_per_million              347773 non-null  float64
 13  total_deaths_per_million                    299086 non-null  float64
 14  new_deaths_per_million                      349089 non-null  float64
 15  new_deaths_smoothed_per_million             347859 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                37853 non-null   float64
 18  icu_patients_per_million                    37853 non-null   float64
 19  hosp_patients                               39263 non-null   float64
 20  hosp_patients_per_million                   39263 non-null   float64
 21  total_tests                                 79387 non-null   float64
 22  new_tests                                   75403 non-null   float64
 23  total_tests_per_thousand                    79387 non-null   float64
 24  new_tests_per_thousand                      75403 non-null   float64
 25  new_tests_smoothed                          103965 non-null  float64
 26  new_tests_smoothed_per_thousand             103965 non-null  float64
 27  positive_rate                               95927 non-null   float64
 28  tests_per_case                              94348 non-null   float64
 29  tests_units                                 106788 non-null  object
 30  total_vaccinations                          80162 non-null   float64
 31  people_vaccinated                           76724 non-null   float64
 32  people_fully_vaccinated                     73420 non-null   float64
 33  total_boosters                              48358 non-null   float64
 34  new_vaccinations                            66124 non-null   float64
 35  new_vaccinations_smoothed                   184057 non-null  float64
 36  total_vaccinations_per_hundred              80162 non-null   float64
 37  people_vaccinated_per_hundred               76724 non-null   float64
 38  people_fully_vaccinated_per_hundred         73420 non-null   float64
 39  total_boosters_per_hundred                  48358 non-null   float64
 40  new_vaccinations_smoothed_per_million       184057 non-null  float64
 41  new_people_vaccinated_smoothed              183804 non-null  float64
 42  new_people_vaccinated_smoothed_per_hundred  183804 non-null  float64
 43  stringency_index                            197651 non-null  float64
 44  population_density                          304672 non-null  float64
 45  median_age                                  283301 non-null  float64
 46  aged_65_older                               273432 non-null  float64
 47  aged_70_older                               280461 non-null  float64
 48  gdp_per_capita                              277692 non-null  float64
 49  extreme_poverty                             179007 non-null  float64
 50  cardiovasc_death_rate                       278348 non-null  float64
 51  diabetes_prevalence                         292517 non-null  float64
 52  female_smokers                              208840 non-null  float64
 53  male_smokers                                206000 non-null  float64
 54  handwashing_facilities                      136345 non-null  float64
 55  hospital_beds_per_thousand                  245760 non-null  float64
 56  life_expectancy                             330161 non-null  float64
 57  human_development_index                     269789 non-null  float64
 58  population                                  358838 non-null  float64
dtypes: float64(54), object(5)
memory usage: 161.5+ MB

============================================================
Data type of 'date' column after conversion: datetime64[ns]

============================================================
Column info after conversion:


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 358838 entries, 0 to 358837
Data columns (total 59 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    358838 non-null  object
 1   continent                                   341730 non-null  object
 2   location                                    358838 non-null  object
 3   date                                        358838 non-null  datetime64[ns]
 4   total_cases                                 320628 non-null  float64
 5   new_cases                                   349032 non-null  float64
 6   new_cases_smoothed                          347773 non-null  float64
 7   total_deaths                                299086 non-null  float64
 8   new_deaths                                  349089 non-null  float64
 9   new_deaths_smoothed                         347859 non-null  float64
 10  total_cases_per_million                     320628 non-null  float64
 11  new_cases_per_million                       349032 non-null  float64
 12  new_cases_smoothed_per_million              347773 non-null  float64
 13  total_deaths_per_million                    299086 non-null  float64
 14  new_deaths_per_million                      349089 non-null  float64
 15  new_deaths_smoothed_per_million             347859 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                37853 non-null   float64
 18  icu_patients_per_million                    37853 non-null   float64
 19  hosp_patients                               39263 non-null   float64
 20  hosp_patients_per_million                   39263 non-null   float64
 21  total_tests                                 79387 non-null   float64
 22  new_tests                                   75403 non-null   float64
 23  total_tests_per_thousand                    79387 non-null   float64
 24  new_tests_per_thousand                      75403 non-null   float64
 25  new_tests_smoothed                          103965 non-null  float64
 26  new_tests_smoothed_per_thousand             103965 non-null  float64
 27  positive_rate                               95927 non-null   float64
 28  tests_per_case                              94348 non-null   float64
 29  tests_units                                 106788 non-null  object
 30  total_vaccinations                          80162 non-null   float64
 31  people_vaccinated                           76724 non-null   float64
 32  people_fully_vaccinated                     73420 non-null   float64
 33  total_boosters                              48358 non-null   float64
 34  new_vaccinations                            66124 non-null   float64
 35  new_vaccinations_smoothed                   184057 non-null  float64
 36  total_vaccinations_per_hundred              80162 non-null   float64
 37  people_vaccinated_per_hundred               76724 non-null   float64
 38  people_fully_vaccinated_per_hundred         73420 non-null   float64
 39  total_boosters_per_hundred                  48358 non-null   float64
 40  new_vaccinations_smoothed_per_million       184057 non-null  float64
 41  new_people_vaccinated_smoothed              183804 non-null  float64
 42  new_people_vaccinated_smoothed_per_hundred  183804 non-null  float64
 43  stringency_index                            197651 non-null  float64
 44  population_density                          304672 non-null  float64
 45  median_age                                  283301 non-null  float64
 46  aged_65_older                               273432 non-null  float64
 47  aged_70_older                               280461 non-null  float64
 48  gdp_per_capita                              277692 non-null  float64
 49  extreme_poverty                             179007 non-null  float64
 50  cardiovasc_death_rate                       278348 non-null  float64
 51  diabetes_prevalence                         292517 non-null  float64
 52  female_smokers                              208840 non-null  float64
 53  male_smokers                                206000 non-null  float64
 54  handwashing_facilities                      136345 non-null  float64
 55  hospital_beds_per_thousand                  245760 non-null  float64
 56  life_expectancy                             330161 non-null  float64
 57  human_development_index                     269789 non-null  float64
 58  population                                  358838 non-null  float64
dtypes: datetime64[ns](1), float64(54), object(4)
memory usage: 161.5+ MB

============================================================
Total number of columns: 59
Number of columns with missing values: 55
Number of numerical columns with missing values: 53
Number of non-numerical columns with missing values: 2

============================================================
Number of numerical columns with missing values: 53
Use the built-in mean() function to replace missing values in numerical columns. Mean is a common method for imputing missing numerical values when the data is not heavily skewed, as it represents the central tendency of the data.

Number of remaining missing values per column after numerical imputation:
iso_code                                           0
continent                                      17108
location                                           0
date                                               0
total_cases                                        0
new_cases                                          0
new_cases_smoothed                                 0
total_deaths                                       0
new_deaths                                         0
new_deaths_smoothed                                0
total_cases_per_million                            0
new_cases_per_million                              0
new_cases_smoothed_per_million                     0
total_deaths_per_million                           0
new_deaths_per_million                             0
new_deaths_smoothed_per_million                    0
reproduction_rate                                  0
icu_patients                                       0
icu_patients_per_million                           0
hosp_patients                                      0
hosp_patients_per_million                          0
total_tests                                        0
new_tests                                          0
total_tests_per_thousand                           0
new_tests_per_thousand                             0
new_tests_smoothed                                 0
new_tests_smoothed_per_thousand                    0
positive_rate                                      0
tests_per_case                                     0
tests_units                                   252050
total_vaccinations                                 0
people_vaccinated                                  0
people_fully_vaccinated                            0
total_boosters                                     0
new_vaccinations                                   0
new_vaccinations_smoothed                          0
total_vaccinations_per_hundred                     0
people_vaccinated_per_hundred                      0
people_fully_vaccinated_per_hundred                0
total_boosters_per_hundred                         0
new_vaccinations_smoothed_per_million              0
new_people_vaccinated_smoothed                     0
new_people_vaccinated_smoothed_per_hundred         0
stringency_index                                   0
population_density                                 0
median_age                                         0
aged_65_older                                      0
aged_70_older                                      0
gdp_per_capita                                     0
extreme_poverty                                    0
cardiovasc_death_rate                              0
diabetes_prevalence                                0
female_smokers                                     0
male_smokers                                       0
handwashing_facilities                             0
hospital_beds_per_thousand                         0
life_expectancy                                    0
human_development_index                            0
population                                         0
dtype: int64

============================================================
Number of non-numerical columns with missing values: 2
Use the built-in mode() function to replace missing values in non-numerical columns. Mode is suitable for categorical columns as it represents the most frequent category, making it ideal for filling missing values in discrete data where mean is not applicable.

Number of remaining missing values per column after non-numerical imputation:
iso_code                                      0
continent                                     0

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,year,month
0,AFG,Asia,Afghanistan,2020-01-03,6.862419e+06,0.0,9409.255662,86954.368292,0.0,83.807025,...,9.59,10.793543,32.910129,37.746,0.5,64.83,0.511,41128772.0,2020,1
1,AFG,Asia,Afghanistan,2020-01-04,6.862419e+06,0.0,9409.255662,86954.368292,0.0,83.807025,...,9.59,10.793543,32.910129,37.746,0.5,64.83,0.511,41128772.0,2020,1
2,AFG,Asia,Afghanistan,2020-01-05,6.862419e+06,0.0,9409.255662,86954.368292,0.0,83.807025,...,9.59,10.793543,32.910129,37.746,0.5,64.83,0.511,41128772.0,2020,1
3,AFG,Asia,Afghanistan,2020-01-06,6.862419e+06,0.0,9409.255662,86954.368292,0.0,83.807025,...,9.59,10.793543,32.910129,37.746,0.5,64.83,0.511,41128772.0,2020,1
4,AFG,Asia,Afghanistan,2020-01-07,6.862419e+06,0.0,9409.255662,86954.368292,0.0,83.807025,...,9.59,10.793543,32.910129,37.746,0.5,64.83,0.511,41128772.0,2020,1

============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 358838 entries, 0 to 358837
Data columns (total 61 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    358838 non-null  object
 1   continent                                   358838 non-null  object
 2   location                                    358838 non-null  object
 3   date                                        358838 non-null  datetime64[ns]
 4   total_cases                                 358838 non-null  float64
 5   new_cases                                   358838 non-null  float64
 6   new_cases_smoothed                          358838 non-null  float64
 7   total_deaths                                358838 non-null  float64
 8   new_deaths                                  358838 non-null  float64
 9   new_deaths_smoothed                         358838 non-null  float64
 10  total_cases_per_million                     358838 non-null  float64
 11  new_cases_per_million                       358838 non-null  float64
 12  new_cases_smoothed_per_million              358838 non-null  float64
 13  total_deaths_per_million                    358838 non-null  float64
 14  new_deaths_per_million                      358838 non-null  float64
 15  new_deaths_smoothed_per_million             358838 non-null  float64
 16  reproduction_rate                           358838 non-null  float64
 17  icu_patients                                358838 non-null  float64
 18  icu_patients_per_million                    358838 non-null  float64
 19  hosp_patients                               358838 non-null  float64
 20  hosp_patients_per_million                   358838 non-null  float64
 21  total_tests                                 358838 non-null  float64
 22  new_tests                                   358838 non-null  float64
 23  total_tests_per_thousand                    358838 non-null  float64
 24  new_tests_per_thousand                      358838 non-null  float64
 25  new_tests_smoothed                          358838 non-null  float64
 26  new_tests_smoothed_per_thousand             358838 non-null  float64
 27  positive_rate                               358838 non-null  float64
 28  tests_per_case                              358838 non-null  float64
 29  tests_units                                 358838 non-null  object
 30  total_vaccinations                          358838 non-null  float64
 31  people_vaccinated                           358838 non-null  float64
 32  people_fully_vaccinated                     358838 non-null  float64
 33  total_boosters                              358838 non-null  float64
 34  new_vaccinations                            358838 non-null  float64
 35  new_vaccinations_smoothed                   358838 non-null  float64
 36  total_vaccinations_per_hundred              358838 non-null  float64
 37  people_vaccinated_per_hundred               358838 non-null  float64
 38  people_fully_vaccinated_per_hundred         358838 non-null  float64
 39  total_boosters_per_hundred                  358838 non-null  float64
 40  new_vaccinations_smoothed_per_million       358838 non-null  float64
 41  new_people_vaccinated_smoothed              358838 non-null  float64
 42  new_people_vaccinated_smoothed_per_hundred  358838 non-null  float64
 43  stringency_index                            358838 non-null  float64
 44  population_density                          358838 non-null  float64
 45  median_age                                  358838 non-null  float64
 46  aged_65_older                               358838 non-null  float64
 47  aged_70_older                               358838 non-null  float64
 48  gdp_per_capita                              358838 non-null  float64
 49  extreme_poverty                             358838 non-null  float64
 50  cardiovasc_death_rate                       358838 non-null  float64
 51  diabetes_prevalence                         358838 non-null  float64
 52  female_smokers                              358838 non-null  float64
 53  male_smokers                                358838 non-null  float64
 54  handwashing_facilities                      358838 non-null  float64
 55  hospital_beds_per_thousand                  358838 non-null  float64
 56  life_expectancy                             358838 non-null  float64
 57  human_development_index                     358838 non-null  float64
 58  population                                  358838 non-null  float64
 59  year                                        358838 non-null  int32
 60  month                                       358838 non-null  int32
dtypes: datetime64[ns](1), float64(54), int32(2), object(4)
memory usage: 164.3+ MB

============================================================
Total number of unique countries: 255

============================================================

List of unique countries:
['Afghanistan' 'Africa' 'Albania' 'Algeria' 'American Samoa' 'Andorra'
 'Angola' 'Anguilla' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba'
 'Asia' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain'
 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda'
 'Bhutan' 'Bolivia' 'Bonaire Sint Eustatius and Saba'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'British Virgin Islands'
 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon'
 'Canada' 'Cape Verde' 'Cayman Islands' 'Central African Republic' 'Chad'
 'Chile' 'China' 'Colombia' 'Comoros' 'Congo' 'Cook Islands' 'Costa Rica'
 "Cote d'Ivoire" 'Croatia' 'Cuba' 'Curacao' 'Cyprus' 'Czechia'
 'Democratic Republic of Congo' 'Denmark' 'Djibouti' 'Dominica'
 'Dominican Republic' 'Ecuador' 'Egypt' 'El Salvador' 'England'
 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia' 'Europe'
 'European Union' 'Faeroe Islands' 'Falkland Islands' 'Fiji' 'Finland'
 'France' 'French Guiana' 'French Polynesia' 'Gabon' 'Gambia' 'Georgia'
 'Germany' 'Ghana' 'Gibraltar' 'Greece' 'Greenland' 'Grenada' 'Guadeloupe'
 'Guam' 'Guatemala' 'Guernsey' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'High income' 'Honduras' 'Hong Kong' 'Hungary' 'Iceland' 'India'
 'Indonesia' 'Iran' 'Iraq' 'Ireland' 'Isle of Man' 'Israel' 'Italy'
 'Jamaica' 'Japan' 'Jersey' 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati'
 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia' 'Lebanon' 'Lesotho'
 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Low income'
 'Lower middle income' 'Luxembourg' 'Macao' 'Madagascar' 'Malawi'
 'Malaysia' 'Maldives' 'Mali' 'Malta' 'Marshall Islands' 'Martinique'
 'Mauritania' 'Mauritius' 'Mayotte' 'Mexico' 'Micronesia (country)'
 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Montserrat' 'Morocco'
 'Mozambique' 'Myanmar' 'Namibia' 'Nauru' 'Nepal' 'Netherlands'
 'New Caledonia' 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'Niue'
 'North America' 'North Korea' 'North Macedonia' 'Northern Cyprus'
 'Northern Ireland' 'Northern Mariana Islands' 'Norway' 'Oceania' 'Oman'
 'Pakistan' 'Palau' 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay'
 'Peru' 'Philippines' 'Pitcairn' 'Poland' 'Portugal' 'Puerto Rico' 'Qatar'
 'Reunion' 'Romania' 'Russia' 'Rwanda' 'Saint Barthelemy' 'Saint Helena'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Martin (French part)'
 'Saint Pierre and Miquelon' 'Saint Vincent and the Grenadines' 'Samoa'
 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Scotland' 'Senegal'
 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore'
 'Sint Maarten (Dutch part)' 'Slovakia' 'Slovenia' 'Solomon Islands'
 'Somalia' 'South Africa' 'South America' 'South Korea' 'South Sudan'
 'Spain' 'Sri Lanka' 'Sudan' 'Suriname' 'Sweden' 'Switzerland' 'Syria'
 'Taiwan' 'Tajikistan' 'Tanzania' 'Thailand' 'Timor' 'Togo' 'Tokelau'
 'Tonga' 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Turkmenistan'
 'Turks and Caicos Islands' 'Tuvalu' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'United Kingdom' 'United States'
 'United States Virgin Islands' 'Upper middle income' 'Uruguay'
 'Uzbekistan' 'Vanuatu' 'Vatican' 'Venezuela' 'Vietnam' 'Wales'
 'Wallis and Futuna' 'Western Sahara' 'World' 'Yemen' 'Zambia' 'Zimbabwe']