<a href="https://colab.research.google.com/github/LS10432/PDDS-PYD-0825-06Oct2025B/blob/main/Project/A2/A2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

# Load the data
df = pd.read_csv('/content/owid-covid-data.csv')
print(f"Number of columns before removal: {df.shape[1]}")
print(f"Total number of rows: {df.shape[0]}")

# Display head and tail
print("\n" + "="*60)
print("Display the first 5 rows of the DataFrame.")
print("\n" + "="*60)
display(df.head())

print("\n" + "="*60)
print("Display the last 5 rows of the DataFrame.")
print("\n" + "="*60)
display(df.tail())

# Check for missing values and identify columns to drop
missing_values_percentage = df.isnull().mean() * 100
columns_to_drop = missing_values_percentage[missing_values_percentage > 90].index.tolist()
print("\nColumns with more than 90% missing values:")
print(columns_to_drop)
print(f"\nNumber of columns to be dropped: {len(columns_to_drop)}")

# Remove columns
df = df.drop(columns=columns_to_drop)

print(f"\nNumber of columns after removal: {df.shape[1]}")
display(df.columns)

# convert 'date' column to datetime data type
df['date'] = pd.to_datetime(df['date'])
print("\n" + "="*60)
print("\nColumn info after datetime conversion:")
df.info()

Number of columns before removal: 67
Total number of rows: 358838

============================================================
Display the first 5 rows of the DataFrame.

============================================================

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-03,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-04,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-05,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-06,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-07,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN

============================================================
Display the last 5 rows of the DataFrame.

============================================================

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
358833,ZWE,Africa,Zimbabwe,2023-11-18,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358834,ZWE,Africa,Zimbabwe,2023-11-19,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358835,ZWE,Africa,Zimbabwe,2023-11-20,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358836,ZWE,Africa,Zimbabwe,2023-11-21,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358837,ZWE,Africa,Zimbabwe,2023-11-22,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN

Columns with more than 90% missing values:
['weekly_icu_admissions', 'weekly_icu_admissions_per_million', 'weekly_hosp_admissions', 'weekly_hosp_admissions_per_million', 'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative', 'excess_mortality', 'excess_mortality_cumulative_per_million']

Number of columns to be dropped: 8

Number of columns after removal: 59

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'stringency_index',
       'population_density', 'median_age', 'aged_65_older', 'aged_70_older',
       'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate',
       'diabetes_prevalence', 'female_smokers', 'male_smokers',
       'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index', 'population'],
      dtype='object')

============================================================

Column info after datetime conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 358838 entries, 0 to 358837
Data columns (total 59 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    358838 non-null  object
 1   continent                                   341730 non-null  object
 2   location                                    358838 non-null  object
 3   date                                        358838 non-null  datetime64[ns]
 4   total_cases                                 320628 non-null  float64
 5   new_cases                                   349032 non-null  float64
 6   new_cases_smoothed                          347773 non-null  float64
 7   total_deaths                                299086 non-null  float64
 8   new_deaths                                  349089 non-null  float64
 9   new_deaths_smoothed                         347859 non-null  float64
 10  total_cases_per_million                     320628 non-null  float64
 11  new_cases_per_million                       349032 non-null  float64
 12  new_cases_smoothed_per_million              347773 non-null  float64
 13  total_deaths_per_million                    299086 non-null  float64
 14  new_deaths_per_million                      349089 non-null  float64
 15  new_deaths_smoothed_per_million             347859 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                37853 non-null   float64
 18  icu_patients_per_million                    37853 non-null   float64
 19  hosp_patients                               39263 non-null   float64
 20  hosp_patients_per_million                   39263 non-null   float64
 21  total_tests                                 79387 non-null   float64
 22  new_tests                                   75403 non-null   float64
 23  total_tests_per_thousand                    79387 non-null   float64
 24  new_tests_per_thousand                      75403 non-null   float64
 25  new_tests_smoothed                          103965 non-null  float64
 26  new_tests_smoothed_per_thousand             103965 non-null  float64
 27  positive_rate                               95927 non-null   float64
 28  tests_per_case                              94348 non-null   float64
 29  tests_units                                 106788 non-null  object
 30  total_vaccinations                          80162 non-null   float64
 31  people_vaccinated                           76724 non-null   float64
 32  people_fully_vaccinated                     73420 non-null   float64
 33  total_boosters                              48358 non-null   float64
 34  new_vaccinations                            66124 non-null   float64
 35  new_vaccinations_smoothed                   184057 non-null  float64
 36  total_vaccinations_per_hundred              80162 non-null   float64
 37  people_vaccinated_per_hundred               76724 non-null   float64
 38  people_fully_vaccinated_per_hundred         73420 non-null   float64
 39  total_boosters_per_hundred                  48358 non-null   float64
 40  new_vaccinations_smoothed_per_million       184057 non-null  float64
 41  new_people_vaccinated_smoothed              183804 non-null  float64
 42  new_people_vaccinated_smoothed_per_hundred  183804 non-null  float64
 43  stringency_index                            197651 non-null  float64
 44  population_density                          304672 non-null  float64
 45  median_age                                  283301 non-null  float64
 46  aged_65_older                               273432 non-null  float64
 47  aged_70_older                               280461 non-null  float64
 48  gdp_per_capita                              277692 non-null  float64
 49  extreme_poverty                             179007 non-null  float64
 50  cardiovasc_death_rate                       278348 non-null  float64
 51  diabetes_prevalence                         292517 non-null  float64
 52  female_smokers                              208840 non-null  float64
 53  male_smokers                                206000 non-null  float64
 54  handwashing_facilities                      136345 non-null  float64
 55  hospital_beds_per_thousand                  245760 non-null  float64
 56  life_expectancy                             330161 non-null  float64
 57  human_development_index                     269789 non-null  float64
 58  population                                  358838 non-null  float64
dtypes: datetime64[ns](1), float64(54), object(4)
memory usage: 161.5+ MB