<a href="https://colab.research.google.com/github/LS10432/PDDS-PYD-0825-06Oct2025B/blob/main/Project/A2/A2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Load the data
df = pd.read_csv('/content/owid-covid-data.csv')
print(f"Number of columns before removal: {df.shape[1]}")
print(f"Total number of rows: {df.shape[0]}")

# Display head and tail
print("\n" + "="*60)
print("Display the first 5 rows of the DataFrame.")
print("\n" + "="*60)
display(df.head())

print("\n" + "="*60)
print("Display the last 5 rows of the DataFrame.")
print("\n" + "="*60)
display(df.tail())

# Check for missing values and identify columns to drop
missing_values_percentage = df.isnull().mean() * 100
columns_to_drop = missing_values_percentage[missing_values_percentage > 90].index.tolist()
print("\nColumns with more than 90% missing values:")
print(columns_to_drop)
print(f"\nNumber of columns to be dropped: {len(columns_to_drop)}")

# Remove columns
df = df.drop(columns=columns_to_drop)

print(f"\nNumber of columns after removal: {df.shape[1]}")
display(df.columns)

# convert 'date' column to datetime data type
df['date'] = pd.to_datetime(df['date'])
print("\n" + "="*60)
print("\nColumn info after datetime conversion:")
df.info()

Number of columns before removal: 67
Total number of rows: 358838

============================================================
Display the first 5 rows of the DataFrame.

============================================================

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-03,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-04,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-05,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-06,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-07,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN

============================================================
Display the last 5 rows of the DataFrame.

============================================================

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
358833,ZWE,Africa,Zimbabwe,2023-11-18,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358834,ZWE,Africa,Zimbabwe,2023-11-19,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358835,ZWE,Africa,Zimbabwe,2023-11-20,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358836,ZWE,Africa,Zimbabwe,2023-11-21,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358837,ZWE,Africa,Zimbabwe,2023-11-22,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN

Columns with more than 90% missing values:
['weekly_icu_admissions', 'weekly_icu_admissions_per_million', 'weekly_hosp_admissions', 'weekly_hosp_admissions_per_million', 'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative', 'excess_mortality', 'excess_mortality_cumulative_per_million']

Number of columns to be dropped: 8

Number of columns after removal: 59

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'stringency_index',
       'population_density', 'median_age', 'aged_65_older', 'aged_70_older',
       'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate',
       'diabetes_prevalence', 'female_smokers', 'male_smokers',
       'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index', 'population'],
      dtype='object')

============================================================

Column info after datetime conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 358838 entries, 0 to 358837
Data columns (total 59 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    358838 non-null  object
 1   continent                                   341730 non-null  object
 2   location                                    358838 non-null  object
 3   date                                        358838 non-null  datetime64[ns]
 4   total_cases                                 320628 non-null  float64
 5   new_cases                                   349032 non-null  float64
 6   new_cases_smoothed                          347773 non-null  float64
 7   total_deaths                                299086 non-null  float64
 8   new_deaths                                  349089 non-null  float64
 9   new_deaths_smoothed                         347859 non-null  float64
 10  total_cases_per_million                     320628 non-null  float64
 11  new_cases_per_million                       349032 non-null  float64
 12  new_cases_smoothed_per_million              347773 non-null  float64
 13  total_deaths_per_million                    299086 non-null  float64
 14  new_deaths_per_million                      349089 non-null  float64
 15  new_deaths_smoothed_per_million             347859 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                37853 non-null   float64
 18  icu_patients_per_million                    37853 non-null   float64
 19  hosp_patients                               39263 non-null   float64
 20  hosp_patients_per_million                   39263 non-null   float64
 21  total_tests                                 79387 non-null   float64
 22  new_tests                                   75403 non-null   float64
 23  total_tests_per_thousand                    79387 non-null   float64
 24  new_tests_per_thousand                      75403 non-null   float64
 25  new_tests_smoothed                          103965 non-null  float64
 26  new_tests_smoothed_per_thousand             103965 non-null  float64
 27  positive_rate                               95927 non-null   float64
 28  tests_per_case                              94348 non-null   float64
 29  tests_units                                 106788 non-null  object
 30  total_vaccinations                          80162 non-null   float64
 31  people_vaccinated                           76724 non-null   float64
 32  people_fully_vaccinated                     73420 non-null   float64
 33  total_boosters                              48358 non-null   float64
 34  new_vaccinations                            66124 non-null   float64
 35  new_vaccinations_smoothed                   184057 non-null  float64
 36  total_vaccinations_per_hundred              80162 non-null   float64
 37  people_vaccinated_per_hundred               76724 non-null   float64
 38  people_fully_vaccinated_per_hundred         73420 non-null   float64
 39  total_boosters_per_hundred                  48358 non-null   float64
 40  new_vaccinations_smoothed_per_million       184057 non-null  float64
 41  new_people_vaccinated_smoothed              183804 non-null  float64
 42  new_people_vaccinated_smoothed_per_hundred  183804 non-null  float64
 43  stringency_index                            197651 non-null  float64
 44  population_density                          304672 non-null  float64
 45  median_age                                  283301 non-null  float64
 46  aged_65_older                               273432 non-null  float64
 47  aged_70_older                               280461 non-null  float64
 48  gdp_per_capita                              277692 non-null  float64
 49  extreme_poverty                             179007 non-null  float64
 50  cardiovasc_death_rate                       278348 non-null  float64
 51  diabetes_prevalence                         292517 non-null  float64
 52  female_smokers                              208840 non-null  float64
 53  male_smokers                                206000 non-null  float64
 54  handwashing_facilities                      136345 non-null  float64
 55  hospital_beds_per_thousand                  245760 non-null  float64
 56  life_expectancy                             330161 non-null  float64
 57  human_development_index                     269789 non-null  float64
 58  population                                  358838 non-null  float64
dtypes: datetime64[ns](1), float64(54), object(4)
memory usage: 161.5+ MB

# Activity 2: Data Cleaning and Feature Engineering
Clean the data by removing duplicate rows, imputing missing values, and creating new features. Then, explore the unique countries in the dataset.

## Remove duplicate rows

### Subtask:
Remove duplicate rows from the DataFrame and show the count of rows before and after removal, as well as the number of duplicate and unique duplicate rows.

**Reasoning**:
I need to remove duplicate rows from the DataFrame and show the count of rows before and after removal, as well as the number of duplicate and unique duplicate rows. I will perform all the steps in a single code block.

In [ ]:
# Get the number of rows before removing duplicates
rows_before = df.shape[0]

# Count the number of duplicate rows
duplicate_rows = df.duplicated().sum()

# Count the number of unique duplicate rows
unique_duplicate_rows = df[df.duplicated()].shape[0]

# Remove duplicate rows
df = df.drop_duplicates()

# Get the number of rows after removing duplicates
rows_after = df.shape[0]

# Print the results
print(f"Number of rows before removing duplicates: {rows_before}")
print(f"Number of duplicate rows: {duplicate_rows}")
print(f"Number of unique duplicate rows: {unique_duplicate_rows}")
print(f"Number of rows after removing duplicates: {rows_after}")

Number of rows before removing duplicates: 358838
Number of duplicate rows: 0
Number of unique duplicate rows: 0
Number of rows after removing duplicates: 358838

## Impute missing values

### Subtask:
Impute missing values in the dataset columns using an appropriate method and explain the reasoning.

**Reasoning**:
Impute missing values in numerical and categorical columns using mean and mode respectively, then verify the imputation by checking for remaining missing values.

In [ ]:
# Print the number of missing values per column before imputation
print("Number of missing values per column before imputation:")
print(df.isnull().sum())


# Select numerical columns
numerical_cols = df.select_dtypes(include=['float64', 'int64']).columns

# Impute missing values in numerical columns using the mean
for col in numerical_cols:
    if df[col].isnull().any():
        mean_val = df[col].mean()
        df[col] = df[col].fillna(mean_val)

# Select categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns

# Impute missing values in categorical columns using the mode
for col in categorical_cols:
    if df[col].isnull().any():
        mode_val = df[col].mode()[0] # mode() can return multiple values, take the first
        df[col] = df[col].fillna(mode_val)


# Print the number of remaining missing values per column
print("\nNumber of remaining missing values per column after imputation:")
print(df.isnull().sum())

# Reasoning for imputation methods
print("\nReasoning for imputation methods:")
print("Mean is used for numerical columns because it represents the central tendency of the data and is a common method for imputing missing numerical values when the data is not heavily skewed.")
print("Mode is used for categorical columns because it represents the most frequent category, which is a suitable way to fill missing values in discrete data where the concept of mean is not applicable.")

Number of missing values per column before imputation:
iso_code                                           0
continent                                      17108
location                                           0
date                                               0
total_cases                                    38210
new_cases                                       9806
new_cases_smoothed                             11065
total_deaths                                   59752
new_deaths                                      9749
new_deaths_smoothed                            10979
total_cases_per_million                        38210
new_cases_per_million                           9806
new_cases_smoothed_per_million                 11065
total_deaths_per_million                       59752
new_deaths_per_million                          9749
new_deaths_smoothed_per_million                10979
reproduction_rate                             174021
icu_patients                                  320985
icu_patients_per_million                      320985
hosp_patients                                 319575
hosp_patients_per_million                     319575
total_tests                                   279451
new_tests                                     283435
total_tests_per_thousand                      279451
new_tests_per_thousand                        283435
new_tests_smoothed                            254873
new_tests_smoothed_per_thousand               254873
positive_rate                                 262911
tests_per_case                                264490
tests_units                                   252050
total_vaccinations                            278676
people_vaccinated                             282114
people_fully_vaccinated                       285418
total_boosters                                310480
new_vaccinations                              292714
new_vaccinations_smoothed                     174781
total_vaccinations_per_hundred                278676
people_vaccinated_per_hundred                 282114
people_fully_vaccinated_per_hundred           285418
total_boosters_per_hundred                    310480
new_vaccinations_smoothed_per_million         174781
new_people_vaccinated_smoothed                175034
new_people_vaccinated_smoothed_per_hundred    175034
stringency_index                              161187
population_density                             54166
median_age                                     75537
aged_65_older                                  85406
aged_70_older                                  78377
gdp_per_capita                                 81146
extreme_poverty                               179831
cardiovasc_death_rate                          80490
diabetes_prevalence                            66321
female_smokers                                149998
male_smokers                                  152838
handwashing_facilities                        222493
hospital_beds_per_thousand                    113078
life_expectancy                                28677
human_development_index                        89049
population                                         0
dtype: int64

Number of remaining missing values per column after imputation:
iso_code                                      0
continent                                     0
location                                      0
date                                          0
total_cases                                   0
new_cases                                     0
new_cases_smoothed                            0
total_deaths                                  0
new_deaths                                    0
new_deaths_smoothed                           0
total_cases_per_million                       0
new_cases_per_million                         0
new_cases_smoothed_per_million                0
total_deaths_per_million                      0
new_deaths_per_million                        0
new_deaths_smoothed_per_million               0
reproduction_rate                             0
icu_patients                                  0
icu_patients_per_million                      0
hosp_patients                                 0
hosp_patients_per_million                     0
total_tests                                   0
new_tests                                     0
total_tests_per_thousand                      0
new_tests_per_thousand                        0
new_tests_smoothed                            0
new_tests_smoothed_per_thousand               0
positive_rate                                 0
tests_per_case                                0
tests_units                                   0
total_vaccinations                            0
people_vaccinated                             0
people_fully_vaccinated                       0
total_boosters                                0
new_vaccinations                              0
new_vaccinations_smoothed                     0
total_vaccinations_per_hundred                0
people_vaccinated_per_hundred                 0
people_fully_vaccinated_per_hundred           0
total_boosters_per_hundred                    0
new_vaccinations_smoothed_per_million         0
new_people_vaccinated_smoothed                0
new_people_vaccinated_smoothed_per_hundred    0
stringency_index                              0
population_density                            0
median_age                                    0
aged_65_older                                 0
aged_70_older                                 0
gdp_per_capita                                0
extreme_poverty                               0
cardiovasc_death_rate                         0
diabetes_prevalence                           0
female_smokers                                0
male_smokers                                  0
handwashing_facilities                        0
hospital_beds_per_thousand                    0
life_expectancy                               0
human_development_index                       0
population                                    0
dtype: int64

Reasoning for imputation methods:
Mean is used for numerical columns because it represents the central tendency of the data and is a common method for imputing missing numerical values when the data is not heavily skewed.
Mode is used for categorical columns because it represents the most frequent category, which is a suitable way to fill missing values in discrete data where the concept of mean is not applicable.

## Create new features

### Subtask:
Extract year and month from the 'date' column, explain the reasoning, and what are the uses.

**Reasoning**:
Extract year and month from the 'date' column and explain the utility of this process.

In [ ]:
# Extract year and month from the 'date' column
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month

# Explain the reasoning
print("\nReasoning for extracting year and month:")
print("Extracting year and month from the date column is crucial for time-series analysis. It allows for grouping data by specific time periods, identifying seasonal trends, and comparing metrics across different years and months. This granularity in time data is essential for understanding patterns and changes in the COVID-19 data over time.")

# Display the head of the DataFrame to show the new columns
print("\n" + "="*60)
print("Display the first 5 rows of the DataFrame with 'year' and 'month' columns.")
print("\n" + "="*60)
display(df.head())

Reasoning for extracting year and month:
Extracting year and month from the date column is crucial for time-series analysis. It allows for grouping data by specific time periods, identifying seasonal trends, and comparing metrics across different years and months. This granularity in time data is essential for understanding patterns and changes in the COVID-19 data over time.

============================================================
Display the first 5 rows of the DataFrame with 'year' and 'month' columns.

============================================================

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,year,month
0,AFG,Asia,Afghanistan,2020-01-03,6.862419e+06,0.0,9409.255662,86954.368292,0.0,83.807025,...,9.59,10.793543,32.910129,37.746,0.5,64.83,0.511,41128772.0,2020,1
1,AFG,Asia,Afghanistan,2020-01-04,6.862419e+06,0.0,9409.255662,86954.368292,0.0,83.807025,...,9.59,10.793543,32.910129,37.746,0.5,64.83,0.511,41128772.0,2020,1
2,AFG,Asia,Afghanistan,2020-01-05,6.862419e+06,0.0,9409.255662,86954.368292,0.0,83.807025,...,9.59,10.793543,32.910129,37.746,0.5,64.83,0.511,41128772.0,2020,1
3,AFG,Asia,Afghanistan,2020-01-06,6.862419e+06,0.0,9409.255662,86954.368292,0.0,83.807025,...,9.59,10.793543,32.910129,37.746,0.5,64.83,0.511,41128772.0,2020,1
4,AFG,Asia,Afghanistan,2020-01-07,6.862419e+06,0.0,9409.255662,86954.368292,0.0,83.807025,...,9.59,10.793543,32.910129,37.746,0.5,64.83,0.511,41128772.0,2020,1

## Explore unique countries

### Subtask:
Explore the unique countries in the dataset and count the total number of countries.

**Reasoning**:
Get the unique values from the 'location' column and count them to find the number of unique countries.

In [ ]:
# Get unique countries from the 'location' column
unique_countries = df['location'].unique()

# Count the number of unique countries
num_unique_countries = len(unique_countries)

# Print the total count of unique countries
print(f"Total number of unique countries: {num_unique_countries}")

# Display the list of unique countries (optional, for verification)
print("\nList of unique countries:")
print(unique_countries)

Total number of unique countries: 255

List of unique countries:
['Afghanistan' 'Africa' 'Albania' 'Algeria' 'American Samoa' 'Andorra'
 'Angola' 'Anguilla' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba'
 'Asia' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain'
 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda'
 'Bhutan' 'Bolivia' 'Bonaire Sint Eustatius and Saba'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'British Virgin Islands'
 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon'
 'Canada' 'Cape Verde' 'Cayman Islands' 'Central African Republic' 'Chad'
 'Chile' 'China' 'Colombia' 'Comoros' 'Congo' 'Cook Islands' 'Costa Rica'
 "Cote d'Ivoire" 'Croatia' 'Cuba' 'Curacao' 'Cyprus' 'Czechia'
 'Democratic Republic of Congo' 'Denmark' 'Djibouti' 'Dominica'
 'Dominican Republic' 'Ecuador' 'Egypt' 'El Salvador' 'England'
 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia' 'Europe'
 'European Union' 'Faeroe Islands' 'Falkland Islands' 'Fiji' 'Finland'
 'France' 'French Guiana' 'French Polynesia' 'Gabon' 'Gambia' 'Georgia'
 'Germany' 'Ghana' 'Gibraltar' 'Greece' 'Greenland' 'Grenada' 'Guadeloupe'
 'Guam' 'Guatemala' 'Guernsey' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'High income' 'Honduras' 'Hong Kong' 'Hungary' 'Iceland' 'India'
 'Indonesia' 'Iran' 'Iraq' 'Ireland' 'Isle of Man' 'Israel' 'Italy'
 'Jamaica' 'Japan' 'Jersey' 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati'
 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia' 'Lebanon' 'Lesotho'
 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Low income'
 'Lower middle income' 'Luxembourg' 'Macao' 'Madagascar' 'Malawi'
 'Malaysia' 'Maldives' 'Mali' 'Malta' 'Marshall Islands' 'Martinique'
 'Mauritania' 'Mauritius' 'Mayotte' 'Mexico' 'Micronesia (country)'
 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Montserrat' 'Morocco'
 'Mozambique' 'Myanmar' 'Namibia' 'Nauru' 'Nepal' 'Netherlands'
 'New Caledonia' 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'Niue'
 'North America' 'North Korea' 'North Macedonia' 'Northern Cyprus'
 'Northern Ireland' 'Northern Mariana Islands' 'Norway' 'Oceania' 'Oman'
 'Pakistan' 'Palau' 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay'
 'Peru' 'Philippines' 'Pitcairn' 'Poland' 'Portugal' 'Puerto Rico' 'Qatar'
 'Reunion' 'Romania' 'Russia' 'Rwanda' 'Saint Barthelemy' 'Saint Helena'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Martin (French part)'
 'Saint Pierre and Miquelon' 'Saint Vincent and the Grenadines' 'Samoa'
 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Scotland' 'Senegal'
 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore'
 'Sint Maarten (Dutch part)' 'Slovakia' 'Slovenia' 'Solomon Islands'
 'Somalia' 'South Africa' 'South America' 'South Korea' 'South Sudan'
 'Spain' 'Sri Lanka' 'Sudan' 'Suriname' 'Sweden' 'Switzerland' 'Syria'
 'Taiwan' 'Tajikistan' 'Tanzania' 'Thailand' 'Timor' 'Togo' 'Tokelau'
 'Tonga' 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Turkmenistan'
 'Turks and Caicos Islands' 'Tuvalu' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'United Kingdom' 'United States'
 'United States Virgin Islands' 'Upper middle income' 'Uruguay'
 'Uzbekistan' 'Vanuatu' 'Vatican' 'Venezuela' 'Vietnam' 'Wales'
 'Wallis and Futuna' 'Western Sahara' 'World' 'Yemen' 'Zambia' 'Zimbabwe']

## Summary:

### Data Analysis Key Findings

*   The initial dataset contained 358,838 rows, and no duplicate rows were found.
*   Missing values in numerical columns were imputed using the mean of each column, and missing values in categorical columns were imputed using the mode of each column. After imputation, there were no remaining missing values.
*   New features 'year' and 'month' were successfully extracted from the 'date' column.
*   There are 255 unique locations in the dataset, including countries, continents, income levels, and the 'World' aggregate.

### Insights or Next Steps

*   The data is clean and ready for further analysis, including time-series analysis using the newly created 'year' and 'month' features.
*   Consider exploring the different types of locations (countries, continents, etc.) within the 'location' column for more granular analysis.

# Consolidated

In [21]:
import pandas as pd

# Load the data
df = pd.read_csv('/content/owid-covid-data.csv')
print(f"Number of columns before removal: {df.shape[1]}")
print(f"Total number of rows: {df.shape[0]}")

# Check for missing values and identify columns to drop
missing_values_percentage = df.isnull().mean() * 100
columns_to_drop = missing_values_percentage[missing_values_percentage > 90].index.tolist()
print("\nColumns with more than 90% missing values:")
print(columns_to_drop)
print(f"\nNumber of columns to be dropped: {len(columns_to_drop)}")

# Remove columns
df = df.drop(columns=columns_to_drop)

print(f"\nNumber of columns after removal: {df.shape[1]}")
display(df.columns)

# convert 'date' column to datetime data type
df['date'] = pd.to_datetime(df['date'])
print("\n" + "="*60)
print("\nColumn info after datetime conversion:")
df.info()

# Remove duplicate rows
rows_before = df.shape[0]
duplicate_rows = df.duplicated().sum()
unique_duplicate_rows = df[df.duplicated()].shape[0]
df = df.drop_duplicates()
rows_after = df.shape[0]

print(f"\nNumber of rows before removing duplicates: {rows_before}")
print(f"Number of duplicate rows: {duplicate_rows}")
print(f"Number of unique duplicate rows: {unique_duplicate_rows}")
print(f"Number of rows after removing duplicates: {rows_after}")


# Print the number of missing values per column before imputation
print("\nNumber of missing values per column before imputation:")
print(df.isnull().sum())

# Select numerical columns
numerical_cols = df.select_dtypes(include=['float64', 'int64']).columns

# Impute missing values in numerical columns using the mean
for col in numerical_cols:
    if df[col].isnull().any():
        mean_val = df[col].mean()
        df[col] = df[col].fillna(mean_val)

# Select categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns

# Impute missing values in categorical columns using the mode
for col in categorical_cols:
    if df[col].isnull().any():
        mode_val = df[col].mode()[0] # mode() can return multiple values, take the first
        df[col] = df[col].fillna(mode_val)


# Print the number of remaining missing values per column
print("\nNumber of remaining missing values per column after imputation:")
print(df.isnull().sum())

# Reasoning for imputation methods
print("\nReasoning for imputation methods:")
print("Mean is used for numerical columns because it represents the central tendency of the data and is a common method for imputing missing numerical values when the data is not heavily skewed.")
print("Mode is used for categorical columns because it represents the most frequent category, which is a suitable way to fill missing values in discrete data where the concept of mean is not applicable.")


# Extract year and month from the 'date' column
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month

# Explain the reasoning
print("\nReasoning for extracting year and month:")
print("Extracting year and month from the date column is crucial for time-series analysis. It allows for grouping data by specific time periods, identifying seasonal trends, and comparing metrics across different years and months. This granularity in time data is essential for understanding patterns and changes in the COVID-19 data over time.")

# Get unique countries from the 'location' column
unique_countries = df['location'].unique()

# Count the number of unique countries
num_unique_countries = len(unique_countries)

# Print the total count of unique countries
print(f"\nTotal number of unique countries: {num_unique_countries}")

# Display the list of unique countries (optional, for verification)
print("\nList of unique countries:")
print(unique_countries)

Number of columns before removal: 67
Total number of rows: 358838

Columns with more than 90% missing values:
['weekly_icu_admissions', 'weekly_icu_admissions_per_million', 'weekly_hosp_admissions', 'weekly_hosp_admissions_per_million', 'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative', 'excess_mortality', 'excess_mortality_cumulative_per_million']

Number of columns to be dropped: 8

Number of columns after removal: 59

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'stringency_index',
       'population_density', 'median_age', 'aged_65_older', 'aged_70_older',
       'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate',
       'diabetes_prevalence', 'female_smokers', 'male_smokers',
       'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index', 'population'],
      dtype='object')

============================================================

Column info after datetime conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 358838 entries, 0 to 358837
Data columns (total 59 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    358838 non-null  object
 1   continent                                   341730 non-null  object
 2   location                                    358838 non-null  object
 3   date                                        358838 non-null  datetime64[ns]
 4   total_cases                                 320628 non-null  float64
 5   new_cases                                   349032 non-null  float64
 6   new_cases_smoothed                          347773 non-null  float64
 7   total_deaths                                299086 non-null  float64
 8   new_deaths                                  349089 non-null  float64
 9   new_deaths_smoothed                         347859 non-null  float64
 10  total_cases_per_million                     320628 non-null  float64
 11  new_cases_per_million                       349032 non-null  float64
 12  new_cases_smoothed_per_million              347773 non-null  float64
 13  total_deaths_per_million                    299086 non-null  float64
 14  new_deaths_per_million                      349089 non-null  float64
 15  new_deaths_smoothed_per_million             347859 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                37853 non-null   float64
 18  icu_patients_per_million                    37853 non-null   float64
 19  hosp_patients                               39263 non-null   float64
 20  hosp_patients_per_million                   39263 non-null   float64
 21  total_tests                                 79387 non-null   float64
 22  new_tests                                   75403 non-null   float64
 23  total_tests_per_thousand                    79387 non-null   float64
 24  new_tests_per_thousand                      75403 non-null   float64
 25  new_tests_smoothed                          103965 non-null  float64
 26  new_tests_smoothed_per_thousand             103965 non-null  float64
 27  positive_rate                               95927 non-null   float64
 28  tests_per_case                              94348 non-null   float64
 29  tests_units                                 106788 non-null  object
 30  total_vaccinations                          80162 non-null   float64
 31  people_vaccinated                           76724 non-null   float64
 32  people_fully_vaccinated                     73420 non-null   float64
 33  total_boosters                              48358 non-null   float64
 34  new_vaccinations                            66124 non-null   float64
 35  new_vaccinations_smoothed                   184057 non-null  float64
 36  total_vaccinations_per_hundred              80162 non-null   float64
 37  people_vaccinated_per_hundred               76724 non-null   float64
 38  people_fully_vaccinated_per_hundred         73420 non-null   float64
 39  total_boosters_per_hundred                  48358 non-null   float64
 40  new_vaccinations_smoothed_per_million       184057 non-null  float64
 41  new_people_vaccinated_smoothed              183804 non-null  float64
 42  new_people_vaccinated_smoothed_per_hundred  183804 non-null  float64
 43  stringency_index                            197651 non-null  float64
 44  population_density                          304672 non-null  float64
 45  median_age                                  283301 non-null  float64
 46  aged_65_older                               273432 non-null  float64
 47  aged_70_older                               280461 non-null  float64
 48  gdp_per_capita                              277692 non-null  float64
 49  extreme_poverty                             179007 non-null  float64
 50  cardiovasc_death_rate                       278348 non-null  float64
 51  diabetes_prevalence                         292517 non-null  float64
 52  female_smokers                              208840 non-null  float64
 53  male_smokers                                206000 non-null  float64
 54  handwashing_facilities                      136345 non-null  float64
 55  hospital_beds_per_thousand                  245760 non-null  float64
 56  life_expectancy                             330161 non-null  float64
 57  human_development_index                     269789 non-null  float64
 58  population                                  358838 non-null  float64
dtypes: datetime64[ns](1), float64(54), object(4)
memory usage: 161.5+ MB

Number of rows before removing duplicates: 358838
Number of duplicate rows: 0
Number of unique duplicate rows: 0
Number of rows after removing duplicates: 358838

Number of missing values per column before imputation:
iso_code                                           0
continent                                      17108
location                                           0
date                                               0
total_cases                                    38210
new_cases                                       9806
new_cases_smoothed                             11065
total_deaths                                   59752
new_deaths                                      9749
new_deaths_smoothed                            10979
total_cases_per_million                        38210
new_cases_per_million                           9806
new_cases_smoothed_per_million                 11065
total_deaths_per_million                       59752
new_deaths_per_million                          9749
new_deaths_smoothed_per_million                10979
reproduction_rate                             174021
icu_patients                                  320985
icu_patients_per_million                      320985
hosp_patients                                 319575
hosp_patients_per_million                     319575
total_tests                                   279451
new_tests                                     283435
total_tests_per_thousand                      279451
new_tests_per_thousand                        283435
new_tests_smoothed                            254873
new_tests_smoothed_per_thousand               254873
positive_rate                                 262911
tests_per_case                                264490
tests_units                                   252050
total_vaccinations                            278676
people_vaccinated                             282114
people_fully_vaccinated                       285418
total_boosters                                310480
new_vaccinations                              292714
new_vaccinations_smoothed                     174781
total_vaccinations_per_hundred                278676
people_vaccinated_per_hundred                 282114
people_fully_vaccinated_per_hundred           285418
total_boosters_per_hundred                    310480
new_vaccinations_smoothed_per_million         174781
new_people_vaccinated_smoothed                175034
new_people_vaccinated_smoothed_per_hundred    175034
stringency_index                              161187
population_density                             54166
median_age                                     75537
aged_65_older                                  85406
aged_70_older                                  78377
gdp_per_capita                                 81146
extreme_poverty                               179831
cardiovasc_death_rate                          80490
diabetes_prevalence                            66321
female_smokers                                149998
male_smokers                                  152838
handwashing_facilities                        222493
hospital_beds_per_thousand                    113078
life_expectancy                                28677
human_development_index                        89049
population                                         0
dtype: int64

Number of remaining missing values per column after imputation:
iso_code                                      0
continent                                     0
location                                      0
date                                          0
total_cases                                   0
new_cases                                     0
new_cases_smoothed                            0
total_deaths                                  0
new_deaths                                    0
new_deaths_smoothed                           0
total_cases_per_million                       0
new_cases_per_million                         0
new_cases_smoothed_per_million                0
total_deaths_per_million                      0
new_deaths_per_million                        0
new_deaths_smoothed_per_million               0
reproduction_rate                             0
icu_patients                                  0
icu_patients_per_million                      0
hosp_patients                                 0
hosp_patients_per_million                     0
total_tests                                   0
new_tests                                     0
total_tests_per_thousand                      0
new_tests_per_thousand                        0
new_tests_smoothed                            0
new_tests_smoothed_per_thousand               0
positive_rate                                 0
tests_per_case                                0
tests_units                                   0
total_vaccinations                            0
people_vaccinated                             0
people_fully_vaccinated                       0
total_boosters                                0
new_vaccinations                              0
new_vaccinations_smoothed                     0
total_vaccinations_per_hundred                0
people_vaccinated_per_hundred                 0
people_fully_vaccinated_per_hundred           0
total_boosters_per_hundred                    0
new_vaccinations_smoothed_per_million         0
new_people_vaccinated_smoothed                0
new_people_vaccinated_smoothed_per_hundred    0
stringency_index                              0
population_density                            0
median_age                                    0
aged_65_older                                 0
aged_70_older                                 0
gdp_per_capita                                0
extreme_poverty                               0
cardiovasc_death_rate                         0
diabetes_prevalence                           0
female_smokers                                0
male_smokers                                  0
handwashing_facilities                        0
hospital_beds_per_thousand                    0
life_expectancy                               0
human_development_index                       0
population                                    0
dtype: int64

Reasoning for imputation methods:
Mean is used for numerical columns because it represents the central tendency of the data and is a common method for imputing missing numerical values when the data is not heavily skewed.
Mode is used for categorical columns because it represents the most frequent category, which is a suitable way to fill missing values in discrete data where the concept of mean is not applicable.

Reasoning for extracting year and month:
Extracting year and month from the date column is crucial for time-series analysis. It allows for grouping data by specific time periods, identifying seasonal trends, and comparing metrics across different years and months. This granularity in time data is essential for understanding patterns and changes in the COVID-19 data over time.

Total number of unique countries: 255

List of unique countries:
['Afghanistan' 'Africa' 'Albania' 'Algeria' 'American Samoa' 'Andorra'
 'Angola' 'Anguilla' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba'
 'Asia' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain'
 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda'
 'Bhutan' 'Bolivia' 'Bonaire Sint Eustatius and Saba'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'British Virgin Islands'
 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon'
 'Canada' 'Cape Verde' 'Cayman Islands' 'Central African Republic' 'Chad'
 'Chile' 'China' 'Colombia' 'Comoros' 'Congo' 'Cook Islands' 'Costa Rica'
 "Cote d'Ivoire" 'Croatia' 'Cuba' 'Curacao' 'Cyprus' 'Czechia'
 'Democratic Republic of Congo' 'Denmark' 'Djibouti' 'Dominica'
 'Dominican Republic' 'Ecuador' 'Egypt' 'El Salvador' 'England'
 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia' 'Europe'
 'European Union' 'Faeroe Islands' 'Falkland Islands' 'Fiji' 'Finland'
 'France' 'French Guiana' 'French Polynesia' 'Gabon' 'Gambia' 'Georgia'
 'Germany' 'Ghana' 'Gibraltar' 'Greece' 'Greenland' 'Grenada' 'Guadeloupe'
 'Guam' 'Guatemala' 'Guernsey' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'High income' 'Honduras' 'Hong Kong' 'Hungary' 'Iceland' 'India'
 'Indonesia' 'Iran' 'Iraq' 'Ireland' 'Isle of Man' 'Israel' 'Italy'
 'Jamaica' 'Japan' 'Jersey' 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati'
 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia' 'Lebanon' 'Lesotho'
 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Low income'
 'Lower middle income' 'Luxembourg' 'Macao' 'Madagascar' 'Malawi'
 'Malaysia' 'Maldives' 'Mali' 'Malta' 'Marshall Islands' 'Martinique'
 'Mauritania' 'Mauritius' 'Mayotte' 'Mexico' 'Micronesia (country)'
 'Moldova' 'Monaco' 'Mongolia' 'Montenegro' 'Montserrat' 'Morocco'
 'Mozambique' 'Myanmar' 'Namibia' 'Nauru' 'Nepal' 'Netherlands'
 'New Caledonia' 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'Niue'
 'North America' 'North Korea' 'North Macedonia' 'Northern Cyprus'
 'Northern Ireland' 'Northern Mariana Islands' 'Norway' 'Oceania' 'Oman'
 'Pakistan' 'Palau' 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay'
 'Peru' 'Philippines' 'Pitcairn' 'Poland' 'Portugal' 'Puerto Rico' 'Qatar'
 'Reunion' 'Romania' 'Russia' 'Rwanda' 'Saint Barthelemy' 'Saint Helena'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Martin (French part)'
 'Saint Pierre and Miquelon' 'Saint Vincent and the Grenadines' 'Samoa'
 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Scotland' 'Senegal'
 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore'
 'Sint Maarten (Dutch part)' 'Slovakia' 'Slovenia' 'Solomon Islands'
 'Somalia' 'South Africa' 'South America' 'South Korea' 'South Sudan'
 'Spain' 'Sri Lanka' 'Sudan' 'Suriname' 'Sweden' 'Switzerland' 'Syria'
 'Taiwan' 'Tajikistan' 'Tanzania' 'Thailand' 'Timor' 'Togo' 'Tokelau'
 'Tonga' 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Turkmenistan'
 'Turks and Caicos Islands' 'Tuvalu' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'United Kingdom' 'United States'
 'United States Virgin Islands' 'Upper middle income' 'Uruguay'
 'Uzbekistan' 'Vanuatu' 'Vatican' 'Venezuela' 'Vietnam' 'Wales'
 'Wallis and Futuna' 'Western Sahara' 'World' 'Yemen' 'Zambia' 'Zimbabwe']