<a href="https://colab.research.google.com/github/LS10432/PDDS-PYD-0825-06Oct2025B/blob/main/Project/A1/A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Activity 1: Data Loading and Exploration

Initializing the analysis by loading and exploring the dataset, ensuring data integrity and format consistency for accurate downstream analysis.

## Load data

1. Load the COVID-19 DataFrame using pandas from the provided dataset files.

In [64]:
import pandas as pd

# Define the local path and the URL for the covid dataset
local_path = '/content/owid-covid-data.csv'
covid_url = 'https://lms.educlaas.com/assets/courseware/v1/e206258dd748e86b8bb35fc039e90fa8/asset-v1:EduCLaSS+PYD+PDDS-PYD-0825-06Oct2025B+type@asset+block/owid-covid-data.csv'

try:
    # Try to read the Titanic dataset from the local path
    df = pd.read_csv(local_path)
    print(f"Successfully loaded data from {local_path}")
    print("\n")
except FileNotFoundError:
    # If the local file is not found, read the dataset from the URL
    df = pd.read_csv(covid_url)
    print(f"Local file not found. Loading data from {covid_url}")
    print("\n")

print(f"Total number of columns: {df.shape[1]}")
print(f"Total number of rows: {df.shape[0]}")

Local file not found. Loading data from https://lms.educlaas.com/assets/courseware/v1/e206258dd748e86b8bb35fc039e90fa8/asset-v1:EduCLaSS+PYD+PDDS-PYD-0825-06Oct2025B+type@asset+block/owid-covid-data.csv


Total number of columns: 67
Total number of rows: 358838

## Display head and tail

2. Display the first 5 and last 5 rows of the DataFrame.

In [65]:
# Print a newline followed by a separator line
print("\n" + "="*60)
print("Display the first 5 rows of the DataFrame.")
# Print a newline followed by a separator line
print("\n" + "="*60)
# Print the first 5 rows of the DataFrame
display(df.head())

# Print a newline followed by a separator line
print("\n" + "="*60)
print("Display the last 5 rows of the DataFrame.")
# Print a newline followed by a separator line
print("\n" + "="*60)
# Print the last 5 rows of the DataFrame
display(df.tail())

============================================================
Display the first 5 rows of the DataFrame.

============================================================

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-03,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-04,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-05,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-06,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-07,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN

============================================================
Display the last 5 rows of the DataFrame.

============================================================

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
358833,ZWE,Africa,Zimbabwe,2023-11-18,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358834,ZWE,Africa,Zimbabwe,2023-11-19,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358835,ZWE,Africa,Zimbabwe,2023-11-20,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358836,ZWE,Africa,Zimbabwe,2023-11-21,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358837,ZWE,Africa,Zimbabwe,2023-11-22,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN

## Check missing values

3. Check for missing values in the dataset and decide on a strategy to handle them.

In [66]:
# Identify and count missing values in each column
print(df.isnull().sum())
# Print a newline followed by a separator line
print("\n" + "="*60)

# Calculate columns no missing values
missing_cols = df.isnull().sum() != 0

# Display columns no missing values
print(f"Number of columns with no missing values: {len(missing_cols) - missing_cols.sum()}")
print("Column Names with no missing values:")
display(missing_cols[missing_cols == False].index.tolist())

# Print columns missing values
print("\n" + "="*60)
print(f"Number of columns with missing values: {missing_cols.sum()}")

# Calculate percentage of columns with more than 90% missing values.
missing_values_percentage = df.isnull().mean() * 100
columns_to_drop = missing_values_percentage[missing_values_percentage > 90].index.tolist()

# Display columns with more than 90% missing values
print(f"Number of columns with more than 90% missing values: {len(columns_to_drop)}")
print("Column Names with more than 90% missing values:")
print(columns_to_drop)
print("\n" + "="*60)

iso_code                                        0
continent                                   17108
location                                        0
date                                            0
total_cases                                 38210
                                            ...
population                                      0
excess_mortality_cumulative_absolute       346627
excess_mortality_cumulative                346627
excess_mortality                           346627
excess_mortality_cumulative_per_million    346627
Length: 67, dtype: int64

============================================================
Number of columns with no missing values: 4
Column Names with no missing values:

['iso_code', 'location', 'date', 'population']

============================================================
Number of columns with missing values: 63
Number of columns with more than 90% missing values: 8
Column Names with more than 90% missing values:
['weekly_icu_admissions', 'weekly_icu_admissions_per_million', 'weekly_hosp_admissions', 'weekly_hosp_admissions_per_million', 'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative', 'excess_mortality', 'excess_mortality_cumulative_per_million']

============================================================

## Remove columns

4. Remove the columns with more than 90% of missing values.

In [67]:
# Print number of columns to be dropped
print(f"Number of columns to be dropped: {len(columns_to_drop)}")
print("Column Names to be dropped:")
print(columns_to_drop)

# Remove columns with more than 90% missing values
df = df.drop(columns=columns_to_drop)

# Print a newline
print("\n")

# Display the columns after drop
display(df.columns)

# Print number of columns remaining
print("\n")
print(f"Number of columns after removal: {df.shape[1]}")

Number of columns to be dropped: 8

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'stringency_index',
       'population_density', 'median_age', 'aged_65_older', 'aged_70_older',
       'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate',
       'diabetes_prevalence', 'female_smokers', 'male_smokers',
       'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index', 'population'],
      dtype='object')

Number of columns after removal: 59

## Convert date column

5. Convert the 'date' column to the datetime data type.

In [68]:
# Print a newline followed by a separator line
print("\n" + "="*60)
print("Data type of 'date' column before conversion:")
# Display the data type of the 'date' column
print(df['date'].dtype)

# Print a newline followed by a separator line
print("\n" + "="*60)
print("\nColumn info before conversion:")
# Display summary of the DataFrame
df.info()

# Convert the 'date' column from object type to datetime type
df['date'] = pd.to_datetime(df['date'])

# Print a newline followed by a separator line
print("\n" + "="*60)
print("Data type of 'date' column after conversion:")
# Display the updated data type of the 'date' column
print(df['date'].dtype)

# Print a newline followed by a separator line
print("\n" + "="*60)
print("\nColumn info after conversion:")
# Display summary of the DataFrame
df.info()

============================================================
Data type of 'date' column before conversion:
object

============================================================

Column info before conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 358838 entries, 0 to 358837
Data columns (total 59 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    358838 non-null  object
 1   continent                                   341730 non-null  object
 2   location                                    358838 non-null  object
 3   date                                        358838 non-null  object
 4   total_cases                                 320628 non-null  float64
 5   new_cases                                   349032 non-null  float64
 6   new_cases_smoothed                          347773 non-null  float64
 7   total_deaths                                299086 non-null  float64
 8   new_deaths                                  349089 non-null  float64
 9   new_deaths_smoothed                         347859 non-null  float64
 10  total_cases_per_million                     320628 non-null  float64
 11  new_cases_per_million                       349032 non-null  float64
 12  new_cases_smoothed_per_million              347773 non-null  float64
 13  total_deaths_per_million                    299086 non-null  float64
 14  new_deaths_per_million                      349089 non-null  float64
 15  new_deaths_smoothed_per_million             347859 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                37853 non-null   float64
 18  icu_patients_per_million                    37853 non-null   float64
 19  hosp_patients                               39263 non-null   float64
 20  hosp_patients_per_million                   39263 non-null   float64
 21  total_tests                                 79387 non-null   float64
 22  new_tests                                   75403 non-null   float64
 23  total_tests_per_thousand                    79387 non-null   float64
 24  new_tests_per_thousand                      75403 non-null   float64
 25  new_tests_smoothed                          103965 non-null  float64
 26  new_tests_smoothed_per_thousand             103965 non-null  float64
 27  positive_rate                               95927 non-null   float64
 28  tests_per_case                              94348 non-null   float64
 29  tests_units                                 106788 non-null  object
 30  total_vaccinations                          80162 non-null   float64
 31  people_vaccinated                           76724 non-null   float64
 32  people_fully_vaccinated                     73420 non-null   float64
 33  total_boosters                              48358 non-null   float64
 34  new_vaccinations                            66124 non-null   float64
 35  new_vaccinations_smoothed                   184057 non-null  float64
 36  total_vaccinations_per_hundred              80162 non-null   float64
 37  people_vaccinated_per_hundred               76724 non-null   float64
 38  people_fully_vaccinated_per_hundred         73420 non-null   float64
 39  total_boosters_per_hundred                  48358 non-null   float64
 40  new_vaccinations_smoothed_per_million       184057 non-null  float64
 41  new_people_vaccinated_smoothed              183804 non-null  float64
 42  new_people_vaccinated_smoothed_per_hundred  183804 non-null  float64
 43  stringency_index                            197651 non-null  float64
 44  population_density                          304672 non-null  float64
 45  median_age                                  283301 non-null  float64
 46  aged_65_older                               273432 non-null  float64
 47  aged_70_older                               280461 non-null  float64
 48  gdp_per_capita                              277692 non-null  float64
 49  extreme_poverty                             179007 non-null  float64
 50  cardiovasc_death_rate                       278348 non-null  float64
 51  diabetes_prevalence                         292517 non-null  float64
 52  female_smokers                              208840 non-null  float64
 53  male_smokers                                206000 non-null  float64
 54  handwashing_facilities                      136345 non-null  float64
 55  hospital_beds_per_thousand                  245760 non-null  float64
 56  life_expectancy                             330161 non-null  float64
 57  human_development_index                     269789 non-null  float64
 58  population                                  358838 non-null  float64
dtypes: float64(54), object(5)
memory usage: 161.5+ MB

============================================================
Data type of 'date' column after conversion:
datetime64[ns]

============================================================

Column info after conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 358838 entries, 0 to 358837
Data columns (total 59 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    358838 non-null  object
 1   continent                                   341730 non-null  object
 2   location                                    358838 non-null  object
 3   date                                        358838 non-null  datetime64[ns]
 4   total_cases                                 320628 non-null  float64
 5   new_cases                                   349032 non-null  float64
 6   new_cases_smoothed                          347773 non-null  float64
 7   total_deaths                                299086 non-null  float64
 8   new_deaths                                  349089 non-null  float64
 9   new_deaths_smoothed                         347859 non-null  float64
 10  total_cases_per_million                     320628 non-null  float64
 11  new_cases_per_million                       349032 non-null  float64
 12  new_cases_smoothed_per_million              347773 non-null  float64
 13  total_deaths_per_million                    299086 non-null  float64
 14  new_deaths_per_million                      349089 non-null  float64
 15  new_deaths_smoothed_per_million             347859 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                37853 non-null   float64
 18  icu_patients_per_million                    37853 non-null   float64
 19  hosp_patients                               39263 non-null   float64
 20  hosp_patients_per_million                   39263 non-null   float64
 21  total_tests                                 79387 non-null   float64
 22  new_tests                                   75403 non-null   float64
 23  total_tests_per_thousand                    79387 non-null   float64
 24  new_tests_per_thousand                      75403 non-null   float64
 25  new_tests_smoothed                          103965 non-null  float64
 26  new_tests_smoothed_per_thousand             103965 non-null  float64
 27  positive_rate                               95927 non-null   float64
 28  tests_per_case                              94348 non-null   float64
 29  tests_units                                 106788 non-null  object
 30  total_vaccinations                          80162 non-null   float64
 31  people_vaccinated                           76724 non-null   float64
 32  people_fully_vaccinated                     73420 non-null   float64
 33  total_boosters                              48358 non-null   float64
 34  new_vaccinations                            66124 non-null   float64
 35  new_vaccinations_smoothed                   184057 non-null  float64
 36  total_vaccinations_per_hundred              80162 non-null   float64
 37  people_vaccinated_per_hundred               76724 non-null   float64
 38  people_fully_vaccinated_per_hundred         73420 non-null   float64
 39  total_boosters_per_hundred                  48358 non-null   float64
 40  new_vaccinations_smoothed_per_million       184057 non-null  float64
 41  new_people_vaccinated_smoothed              183804 non-null  float64
 42  new_people_vaccinated_smoothed_per_hundred  183804 non-null  float64
 43  stringency_index                            197651 non-null  float64
 44  population_density                          304672 non-null  float64
 45  median_age                                  283301 non-null  float64
 46  aged_65_older                               273432 non-null  float64
 47  aged_70_older                               280461 non-null  float64
 48  gdp_per_capita                              277692 non-null  float64
 49  extreme_poverty                             179007 non-null  float64
 50  cardiovasc_death_rate                       278348 non-null  float64
 51  diabetes_prevalence                         292517 non-null  float64
 52  female_smokers                              208840 non-null  float64
 53  male_smokers                                206000 non-null  float64
 54  handwashing_facilities                      136345 non-null  float64
 55  hospital_beds_per_thousand                  245760 non-null  float64
 56  life_expectancy                             330161 non-null  float64
 57  human_development_index                     269789 non-null  float64
 58  population                                  358838 non-null  float64
dtypes: datetime64[ns](1), float64(54), object(4)
memory usage: 161.5+ MB

## Summary:

### Data Analysis Key Findings

*   The dataset was successfully loaded into a pandas DataFrame.
*   Columns with more than 90% missing values were identified as: `weekly_icu_admissions`, `weekly_icu_admissions_per_million`, `weekly_hosp_admissions`, `weekly_hosp_admissions_per_million`, `excess_mortality_cumulative_absolute`, `excess_mortality_cumulative`, `excess_mortality`, and `excess_mortality_cumulative_per_million`.
*   These identified columns were successfully removed from the DataFrame.
*   The 'date' column was successfully converted to datetime objects, as confirmed by the data types displayed (`datetime64[ns]`).

### Insights or Next Steps

*   The data is now cleaned regarding highly missing columns and the 'date' column is in a usable format for time-series analysis.
*   Proceed with further data exploration and analysis, such as filtering by location or date range, or calculating new metrics.

# Consolidated

In [72]:
import pandas as pd

# Define the local path and the URL for the covid dataset
local_path = '/content/owid-covid-data.csv'
covid_url = 'https://lms.educlaas.com/assets/courseware/v1/e206258dd748e86b8bb35fc039e90fa8/asset-v1:EduCLaSS+PYD+PDDS-PYD-0825-06Oct2025B+type@asset+block/owid-covid-data.csv'

try:
    # Try to read the Titanic dataset from the local path
    df = pd.read_csv(local_path)
    print(f"Successfully loaded data from {local_path}")
    print("\n")
except FileNotFoundError:
    # If the local file is not found, read the dataset from the URL
    df = pd.read_csv(covid_url)
    print(f"Local file not found. Loading data from {covid_url}")
    print("\n")

print(f"Total number of columns: {df.shape[1]}")
print(f"Total number of rows: {df.shape[0]}")

# Print a newline followed by a separator line
print("\n" + "="*60)
print("Display the first 5 rows of the DataFrame.")
# Print a newline followed by a separator line
print("\n" + "="*60)
# Print the first 5 rows of the DataFrame
display(df.head())

# Print a newline followed by a separator line
print("\n" + "="*60)
print("Display the last 5 rows of the DataFrame.")
# Print a newline followed by a separator line
print("\n" + "="*60)
# Print the last 5 rows of the DataFrame
display(df.tail())

# Identify and count missing values in each column
print(df.isnull().sum())
# Print a newline followed by a separator line
print("\n" + "="*60)

# Display columns with missing values and count how many columns have no missing values
missing_cols = df.isnull().sum() != 0
#display(missing_cols)
print(f"Number of columns with no missing values: {len(missing_cols) - missing_cols.sum()}")
print(f"Number of columns with missing values: {missing_cols.sum()}")

# Print a newline followed by a separator line
print("\n" + "="*60)
print("Columns with no missing values:")
display(missing_cols[missing_cols == False].index.tolist())

print("\n" + "="*60)

missing_values_percentage = df.isnull().mean() * 100
columns_to_drop = missing_values_percentage[missing_values_percentage > 90].index.tolist()

print("Columns with more than 90% missing values:")
print(columns_to_drop)

# Print a newline
print("\n")
print(f"Number of columns to be dropped: {len(columns_to_drop)}")

# Print number of columns to be dropped
print(f"Number of columns to be dropped: {len(columns_to_drop)}")
print("Column Names to be dropped:")
print(columns_to_drop)

# Remove columns with more than 90% missing values
df = df.drop(columns=columns_to_drop)

# Print a newline
print("\n")

# Display the columns after drop
display(df.columns)

# Print number of columns remaining
print("\n")
print(f"Number of columns after removal: {df.shape[1]}")

# Print a newline followed by a separator line
print("\n" + "="*60)
print("Data type of 'date' column before conversion:")
# Display the data type of the 'date' column
print(df['date'].dtype)

# Print a newline followed by a separator line
print("\n" + "="*60)
print("\nColumn info before conversion:")
# Display summary of the DataFrame
df.info()

# Convert the 'date' column from object type to datetime type
df['date'] = pd.to_datetime(df['date'])

# Print a newline followed by a separator line
print("\n" + "="*60)
print("Data type of 'date' column after conversion:")
# Display the updated data type of the 'date' column
print(df['date'].dtype)

# Print a newline followed by a separator line
print("\n" + "="*60)
print("\nColumn info after conversion:")
# Display summary of the DataFrame
df.info()

Local file not found. Loading data from https://lms.educlaas.com/assets/courseware/v1/e206258dd748e86b8bb35fc039e90fa8/asset-v1:EduCLaSS+PYD+PDDS-PYD-0825-06Oct2025B+type@asset+block/owid-covid-data.csv


Total number of columns: 67
Total number of rows: 358838

============================================================
Display the first 5 rows of the DataFrame.

============================================================

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-03,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-04,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-05,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-06,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-07,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN

============================================================
Display the last 5 rows of the DataFrame.

============================================================

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
358833,ZWE,Africa,Zimbabwe,2023-11-18,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358834,ZWE,Africa,Zimbabwe,2023-11-19,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358835,ZWE,Africa,Zimbabwe,2023-11-20,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358836,ZWE,Africa,Zimbabwe,2023-11-21,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
358837,ZWE,Africa,Zimbabwe,2023-11-22,265890.0,0.0,0.0,5725.0,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN

iso_code                                        0
continent                                   17108
location                                        0
date                                            0
total_cases                                 38210
                                            ...
population                                      0
excess_mortality_cumulative_absolute       346627
excess_mortality_cumulative                346627
excess_mortality                           346627
excess_mortality_cumulative_per_million    346627
Length: 67, dtype: int64

============================================================
Number of columns with no missing values: 4
Number of columns with missing values: 63

============================================================
Columns with no missing values:

['iso_code', 'location', 'date', 'population']

============================================================
Columns with more than 90% missing values:
['weekly_icu_admissions', 'weekly_icu_admissions_per_million', 'weekly_hosp_admissions', 'weekly_hosp_admissions_per_million', 'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative', 'excess_mortality', 'excess_mortality_cumulative_per_million']


Number of columns to be dropped: 8
Number of columns to be dropped: 8
Column Names to be dropped:
['weekly_icu_admissions', 'weekly_icu_admissions_per_million', 'weekly_hosp_admissions', 'weekly_hosp_admissions_per_million', 'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative', 'excess_mortality', 'excess_mortality_cumulative_per_million']

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'stringency_index',
       'population_density', 'median_age', 'aged_65_older', 'aged_70_older',
       'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate',
       'diabetes_prevalence', 'female_smokers', 'male_smokers',
       'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index', 'population'],
      dtype='object')

Number of columns after removal: 59

============================================================
Data type of 'date' column before conversion:
object

============================================================

Column info before conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 358838 entries, 0 to 358837
Data columns (total 59 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    358838 non-null  object
 1   continent                                   341730 non-null  object
 2   location                                    358838 non-null  object
 3   date                                        358838 non-null  object
 4   total_cases                                 320628 non-null  float64
 5   new_cases                                   349032 non-null  float64
 6   new_cases_smoothed                          347773 non-null  float64
 7   total_deaths                                299086 non-null  float64
 8   new_deaths                                  349089 non-null  float64
 9   new_deaths_smoothed                         347859 non-null  float64
 10  total_cases_per_million                     320628 non-null  float64
 11  new_cases_per_million                       349032 non-null  float64
 12  new_cases_smoothed_per_million              347773 non-null  float64
 13  total_deaths_per_million                    299086 non-null  float64
 14  new_deaths_per_million                      349089 non-null  float64
 15  new_deaths_smoothed_per_million             347859 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                37853 non-null   float64
 18  icu_patients_per_million                    37853 non-null   float64
 19  hosp_patients                               39263 non-null   float64
 20  hosp_patients_per_million                   39263 non-null   float64
 21  total_tests                                 79387 non-null   float64
 22  new_tests                                   75403 non-null   float64
 23  total_tests_per_thousand                    79387 non-null   float64
 24  new_tests_per_thousand                      75403 non-null   float64
 25  new_tests_smoothed                          103965 non-null  float64
 26  new_tests_smoothed_per_thousand             103965 non-null  float64
 27  positive_rate                               95927 non-null   float64
 28  tests_per_case                              94348 non-null   float64
 29  tests_units                                 106788 non-null  object
 30  total_vaccinations                          80162 non-null   float64
 31  people_vaccinated                           76724 non-null   float64
 32  people_fully_vaccinated                     73420 non-null   float64
 33  total_boosters                              48358 non-null   float64
 34  new_vaccinations                            66124 non-null   float64
 35  new_vaccinations_smoothed                   184057 non-null  float64
 36  total_vaccinations_per_hundred              80162 non-null   float64
 37  people_vaccinated_per_hundred               76724 non-null   float64
 38  people_fully_vaccinated_per_hundred         73420 non-null   float64
 39  total_boosters_per_hundred                  48358 non-null   float64
 40  new_vaccinations_smoothed_per_million       184057 non-null  float64
 41  new_people_vaccinated_smoothed              183804 non-null  float64
 42  new_people_vaccinated_smoothed_per_hundred  183804 non-null  float64
 43  stringency_index                            197651 non-null  float64
 44  population_density                          304672 non-null  float64
 45  median_age                                  283301 non-null  float64
 46  aged_65_older                               273432 non-null  float64
 47  aged_70_older                               280461 non-null  float64
 48  gdp_per_capita                              277692 non-null  float64
 49  extreme_poverty                             179007 non-null  float64
 50  cardiovasc_death_rate                       278348 non-null  float64
 51  diabetes_prevalence                         292517 non-null  float64
 52  female_smokers                              208840 non-null  float64
 53  male_smokers                                206000 non-null  float64
 54  handwashing_facilities                      136345 non-null  float64
 55  hospital_beds_per_thousand                  245760 non-null  float64
 56  life_expectancy                             330161 non-null  float64
 57  human_development_index                     269789 non-null  float64
 58  population                                  358838 non-null  float64
dtypes: float64(54), object(5)
memory usage: 161.5+ MB

============================================================
Data type of 'date' column after conversion:
datetime64[ns]

============================================================

Column info after conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 358838 entries, 0 to 358837
Data columns (total 59 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    358838 non-null  object
 1   continent                                   341730 non-null  object
 2   location                                    358838 non-null  object
 3   date                                        358838 non-null  datetime64[ns]
 4   total_cases                                 320628 non-null  float64
 5   new_cases                                   349032 non-null  float64
 6   new_cases_smoothed                          347773 non-null  float64
 7   total_deaths                                299086 non-null  float64
 8   new_deaths                                  349089 non-null  float64
 9   new_deaths_smoothed                         347859 non-null  float64
 10  total_cases_per_million                     320628 non-null  float64
 11  new_cases_per_million                       349032 non-null  float64
 12  new_cases_smoothed_per_million              347773 non-null  float64
 13  total_deaths_per_million                    299086 non-null  float64
 14  new_deaths_per_million                      349089 non-null  float64
 15  new_deaths_smoothed_per_million             347859 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                37853 non-null   float64
 18  icu_patients_per_million                    37853 non-null   float64
 19  hosp_patients                               39263 non-null   float64
 20  hosp_patients_per_million                   39263 non-null   float64
 21  total_tests                                 79387 non-null   float64
 22  new_tests                                   75403 non-null   float64
 23  total_tests_per_thousand                    79387 non-null   float64
 24  new_tests_per_thousand                      75403 non-null   float64
 25  new_tests_smoothed                          103965 non-null  float64
 26  new_tests_smoothed_per_thousand             103965 non-null  float64
 27  positive_rate                               95927 non-null   float64
 28  tests_per_case                              94348 non-null   float64
 29  tests_units                                 106788 non-null  object
 30  total_vaccinations                          80162 non-null   float64
 31  people_vaccinated                           76724 non-null   float64
 32  people_fully_vaccinated                     73420 non-null   float64
 33  total_boosters                              48358 non-null   float64
 34  new_vaccinations                            66124 non-null   float64
 35  new_vaccinations_smoothed                   184057 non-null  float64
 36  total_vaccinations_per_hundred              80162 non-null   float64
 37  people_vaccinated_per_hundred               76724 non-null   float64
 38  people_fully_vaccinated_per_hundred         73420 non-null   float64
 39  total_boosters_per_hundred                  48358 non-null   float64
 40  new_vaccinations_smoothed_per_million       184057 non-null  float64
 41  new_people_vaccinated_smoothed              183804 non-null  float64
 42  new_people_vaccinated_smoothed_per_hundred  183804 non-null  float64
 43  stringency_index                            197651 non-null  float64
 44  population_density                          304672 non-null  float64
 45  median_age                                  283301 non-null  float64
 46  aged_65_older                               273432 non-null  float64
 47  aged_70_older                               280461 non-null  float64
 48  gdp_per_capita                              277692 non-null  float64
 49  extreme_poverty                             179007 non-null  float64
 50  cardiovasc_death_rate                       278348 non-null  float64
 51  diabetes_prevalence                         292517 non-null  float64
 52  female_smokers                              208840 non-null  float64
 53  male_smokers                                206000 non-null  float64
 54  handwashing_facilities                      136345 non-null  float64
 55  hospital_beds_per_thousand                  245760 non-null  float64
 56  life_expectancy                             330161 non-null  float64
 57  human_development_index                     269789 non-null  float64
 58  population                                  358838 non-null  float64
dtypes: datetime64[ns](1), float64(54), object(4)
memory usage: 161.5+ MB